CREATE TABLE IF NOT EXISTS ACCOUNT (
    Account_ID INT AUTO_INCREMENT PRIMARY KEY,
    Account_Number CHAR(12) UNIQUE NOT NULL,
    Account_Holder_Name VARCHAR(100) NOT NULL,
    Balance DECIMAL(15, 2) DEFAULT 0.00,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PAYEE (
    Payee_ID INT AUTO_INCREMENT PRIMARY KEY,
    Payee_Name VARCHAR(100) NOT NULL,
    Payee_Account_Number CHAR(12) UNIQUE NOT NULL,
    Bank_Name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS RULE (
    Rule_ID INT AUTO_INCREMENT PRIMARY KEY,
    Rule_Name VARCHAR(100) NOT NULL,
    Rule_Type ENUM('THRESHOLD', 'VELOCITY', 'NEW_PAYEE', 'DAILY_LIMIT') NOT NULL,
    Severity ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL') NOT NULL,
    Threshold DECIMAL(15, 2) NULL,
    Time_Window INT NULL,
    Active_Status BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS TRANSACTION_TABLE (
    Transaction_ID INT AUTO_INCREMENT PRIMARY KEY,
    Account_ID INT NOT NULL,
    Payee_ID INT NOT NULL,
    Amount DECIMAL(15, 2) NOT NULL,
    Transaction_Type ENUM('TRANSFER', 'PAYMENT', 'WITHDRAWAL') NOT NULL,
    Time_Stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    KEY IDX_TRANSACTION_ACCOUNT_TIMESTAMP (Account_ID, Time_Stamp),
    FOREIGN KEY (Account_ID) REFERENCES ACCOUNT(Account_ID) ON DELETE RESTRICT,
    FOREIGN KEY (Payee_ID) REFERENCES PAYEE(Payee_ID) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS ALERT (
    Alert_ID INT AUTO_INCREMENT PRIMARY KEY,
    Rule_ID INT NOT NULL,
    Transaction_ID INT NOT NULL,
    Status ENUM('OPEN', 'ACKNOWLEDGED', 'INVESTIGATING', 'CLOSED', 'DISMISSED') DEFAULT 'OPEN',
    Severity ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL') NOT NULL,
    Created_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Updated_At TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Closed_At TIMESTAMP NULL,
    KEY IDX_ALERT_STATUS_CREATED (Status, Created_At),
    FOREIGN KEY (Rule_ID) REFERENCES RULE(Rule_ID) ON DELETE CASCADE,
    FOREIGN KEY (Transaction_ID) REFERENCES TRANSACTION_TABLE(Transaction_ID) ON DELETE CASCADE
);



